version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201903-01
    - run:
      name: Install Docker Compose
      command: |
        curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
        chmod +x ~/docker-compose
        sudo mv ~/docker-compose /usr/local/bin/docker-compose
    - setup_remote_docker
    - run:
      name: Build Docker Container
      command: |
        docker-compose build
        docker-compose up -d