original_intent_list = ["Default Welcome Intent",
                        "Default Fallback Intent",
                        "all_courses_queries",
                        "consultation_booking",
                        "consultation_booking_with_followup-user_input_course_code_with_followup-user_input_time_and_date",
                        "consultation_booking_with_followup-user_input_course_code_with_followup",
                        "consultation_booking_with_followup-user_input_time_and_date_with_followup-user_input_course_code",
                        "consultation_booking_with_followup-user_input_time_and_date_with_followup",
                        "consultation_booking_with_followup",
                        "consultation_cancel",
                        "course_fee_queries",
                        "course_fee_queries_with_followup-user_input_course_code",
                        "course_fee_queries_with_followup",
                        "course_location_queries",
                        "course_location_queries_with_followup-user_input_course_code",
                        "course_location_queries_with_followup",
                        "course_outline_queries",
                        "course_outline_queries_with_followup-user_input_course_code",
                        "course_outline_queries_with_followup",
                        "indicative_hours_queries",
                        "indicative_hours_queries_with_followup-user_input_course_code",
                        "indicative_hours_queries_with_followup",
                        "offering_term_queries",
                        "offering_term_queries_with_followup-user_input_course_code",
                        "offering_term_queries_with_followup",
                        "prerequisites_queries",
                        "prerequisites_queries_with_followup-user_input_course_code",
                        "prerequisites_queries_with_followup",
                        "school_and_faculty_queries",
                        "school_and_faculty_queries_with_followup-user_input_course_code",
                        "school_and_faculty_queries_with_followup",
                        "send_outline_queries",
                        "send_outline_queries_with_followup-user_input_course_code",
                        "send_outline_queries_with_followup",
                        "study_level_queries",
                        "study_level_queries_with_followup-user_input_course_code",
                        "study_level_queries_with_followup",
                        "wam_queries", ]

course_outline_queries = ["What is {course_code} about?",
                          "Tell me more about {course_code}",
                          "What can I learn in {course_code}",
                          "Description of {course_code}",
                          "Course outline for {course_code}",
                          "Give me the course outline of {course_code}",
                          "Give me a description of {course_code}",
                          "I want to know what {course_code} is about",
                          "Describe {course_code} for me",
                          "I want to see the course outline for {course_code}",
                          "Show me the course outline for {course_code}",
                          "I want the outline for {course_code}",
                          "Give me the outline for {course_code}",
                          "{course_code} outline",
                          "{course_code} course outline",
                          "Course description for {course_code} please",
                          "Course description for {course_code}",
                          "Course description for {course_code} thanks",
                          "Course description for {course_code} thank you",
                          "I want to see the course outline for {course_code}",
                          "I want to see the course description for {course_code}",
                          "outline for {course_code}",
                          "Course outline {course_code}",
                          "I want to know about {course_code}",
                          "I want to find out more about {course_code}",
                          "Tell me about {course_code}",
                          "{course_code} description", ]

study_level_queries = ["display_name study_level_queries",
                       "message_texts $course",
                       "intent_types study_level",
                       "reset_contexts",
                       "Is {course_code} for undergraduate?",
                       "is {course_code} for postgraduate?",
                       "Which study level is {course_code}?",
                       "Who can take {course_code}?",
                       "Who is {course_code} offered to?",
                       "What study level is {course_code} offered at?",
                       "Can postgraduate study {course_code}?",
                       "Can undergraduate study {course_code}?",
                       "Tell me the study level for {course_code}",
                       "Give me the study level for {course_code}",
                       "{course_code} study level",
                       "study level for {course_code}",
                       "study level of {course_code}",
                       "Is {course_code} for postgraduate?",
                       "Is {course_code} for undergraduate?",
                       "Is {course_code} for postgrad?",
                       "Is {course_code} for undergrad?",
                       "Is {course_code} for postgraduate??",
                       "Is {course_code} for undergraduate??",
                       "Is {course_code} for postgrad??",
                       "Is {course_code} for undergrad??",
                       "{course_code}'s study level",
                       "{course_code} for postgrad?",
                       "{course_code} for undergrad?",
                       "{course_code} for postgraduate?",
                       "{course_code} for undergraduate?", ]

course_location_queries = ["Where is {course_code} offered at?",
                           "Which campus is {course_code} going to be in?",
                           "Which campus is {course_code} gonna be in?",
                           "Which campus do I go to for {course_code}?",
                           "Where do I go to for {course_code}?",
                           "What is the campus for {course_code}?",
                           "Tell me the campus where {course_code} will be held in",
                           "I want to know the campus for {course_code}",
                           "{course_code} location",
                           "Campus for {course_code}",
                           "Where is {course_code} at?",
                           "Location of {course_code}",
                           "{course_code}'s campus",
                           "{course_code}'s location",
                           "{course_code} location",
                           "{course_code} location please",
                           "{course_code} location thanks",
                           "Where to go for {course_code}?",
                           "Which campus to go for {course_code}?", ]

course_fee_queries = ["How much does {course_code} cost?",
                      "How much does {course_code} cost to do?",
                      "What is the cost of {course_code}?",
                      "Cost of {course_code}",
                      "Cost of {course_code}?",
                      "Cost of {course_code}??",
                      "Cost of {course_code}???",
                      "The cost of {course_code}???",
                      "The cost of {course_code}??",
                      "The cost of {course_code}?",
                      "The cost of {course_code}",
                      "The course fee of {course_code}???",
                      "The fee for {course_code}??",
                      "The course fee for {course_code}?",
                      "The course fee of {course_code}",
                      "How expensive is {course_code}?",
                      "How much do I need to pay for {course_code}?",
                      "How much do I need to pay for {course_code}? thanks",
                      "How much do I need to pay for {course_code}? please",
                      "What is the cost of doing {course_code}?",
                      "What is the course fee for {course_code}?",
                      "Course fee for {course_code}",
                      "Course fee for {course_code} thanks",
                      "Course fee for {course_code} please",
                      "Cost of {course_code} please",
                      "Cost of {course_code} thanks",
                      "Give me the course fee for {course_code}",
                      "I want to know the course fee for {course_code}",
                      "Tell me the cost for {course_code}",
                      "Do I need to pay for {course_code}?",
                      "Please tell me the course fee for {course_code}",
                      "Please tell me the fee for {course_code}",
                      "Please tell me the cost for {course_code}",
                      "Please tell me the cost of {course_code}",
                      "{course_code} fees",
                      "{course_code}'s cost",
                      "{course_code}'s fees",
                      "{course_code}'s course fees",
                      "{course_code} fees thanks",
                      "{course_code}'s cost thanks",
                      "{course_code}'s fees thanks",
                      "{course_code}'s course fees thanks",
                      "{course_code} fees please",
                      "{course_code}'s cost please",
                      "{course_code}'s fees please",
                      "{course_code}'s course fees please",
                      "Tell me about the fees for {course_code}",
                      "Tell me about the cost for {course_code}",
                      "I want to know the cost of {course_code}", ]

indicative_hours_queries = ["What is the indicative hours for {course_code}?",
                            "Tell me the indicative hours for {course_code}",
                            "Give me the indicative hours for {course_code}",
                            "How many hours a week for {course_code}",
                            "How many hours a week for {course_code}?",
                            "How many hours a week for {course_code}??",
                            "How many hours are there for {course_code}?",
                            "How much time will I spend on {course_code}?",
                            "I want to know the indicative hour for {course_code}",
                            "{course_code} indicative hours",
                            "How long will I spend on {course_code}?",
                            "What is the expected work load for {course_code}?",
                            "I want to know the work load for {course_code}",
                            "How many hours of lectures are there for {course_code}?",
                            "How many hours a week are there for {course_code}?",
                            "Will I need to spend lots of time on {course_code}?",
                            "Give me the work load for {course_code}",
                            "Expected work load for {course_code}",
                            "Expected wordload for {course_code}",
                            "{course_code}'s work load",
                            "{course_code}'s workload",
                            "Number of hours for {course_code}",
                            "Number of hours for {course_code}?",
                            "Indicative hours for {course_code}?",
                            "Work load for {course_code}??",
                            "Work load for {course_code}?",
                            "Work load for {course_code}",
                            "Workload for {course_code}??",
                            "Workload for {course_code}??",
                            "Indicative hours for {course_code}??",
                            "Indicative hours for {course_code}???",
                            "Number of hours a week for {course_code}",
                            "Indicative hours a week for {course_code}",
                            ]

prerequisites_queries = [
                        "What classes do I need to take before doing {course_code}?",
                        "What are the prerequisites for {course_code}?",
                        "What courses do I need to take before doing {course_code}?",
                        "Give me the prerequisites for {course_code}.",
                        "Are there any courses I need to do before doing {course_code}?",
                        "Are there any prerequisites for {course_code}?",
                        "What is the condition for enrolment for {course_code}?",
                        "Are there any condition for enrolment for {course_code}?",
                        "Tell me the prerequisites for {course_code}",
                        "What courses do I need to take to be eligible for {course_code}?",
                        "What courses do I need to take to do {course_code}?",
                        "Are there any classes I need to take before doing {course_code}?",
                        "I want to know what classes I need to take before doing {course_code}",
                        "I want to know what courses I need to take before doing {course_code}"
                        "What are the requirements for {course_code}?",
                        "What are the requirements to do {course_code}?",
                        "{course_code} prerequisites",
                        "What courses do I need to take before {course_code}?",
                        "{course_code}'s prerequisites",
                        "{course_code}'s requirements",
                        "prerequisites for {course_code}",
                        "Requirements for {course_code}",
                        ]
import random
intent_list = [['course_fee_queries', course_fee_queries, random.uniform(0.4, 1)],
               ['course_location_queries', course_location_queries, random.uniform(0.75, 1)],
               ['course_outline_queries', indicative_hours_queries, random.uniform(0.8, 1)],
               ['indicative_hours_queries', indicative_hours_queries, random.uniform(0.5, 0.9)],
               ['study_level_queries', study_level_queries, random.uniform(0.66, 0.95)],
               ['prerequisites_queries', prerequisites_queries, random.uniform(0.76, 0.99)]
               ]

course_list = [["COMP6441", "Security Engineering and Cyber Security"],
               ["COMP9020", "Foundations of Computer Science"],
               ["COMP9021", "Principles of Programming"],
               ["COMP9032", "Microprocessors and Interfacing"],
               ["COMP9311", "Database Systems"],
               ["COMP9414", "Artificial Intelligence"],
               ["COMP9814", "Extended Artificial Intelligence"],
               ["COMP9511", "Human Computer Interaction"],
               ["COMP4418", "Knowledge Representation and Reasoning"],
               ["COMP6451", "Cryptocurrency and Distributed Ledger Technologies"],
               ["COMP6324", "Internet of Things Service Design and Engineering"],
               ["COMP9024", "Data Structures and Algorithms"],
               ["COMP9041", "Software Construction: Techniques and Tools"],
               ["COMP9101", "Design & Analysis of Algorithms"],
               ["COMP9801", "Extended Design & Analysis of Algorithms"],
               ["COMP9222", "Digital Circuits and Systems"],
               ["COMP9321", "Data Services Engineering"],
               ["COMP9322", "Software Service Design and Engineering"],
               ["COMP9331", "Computer Networks and Applications"],
               ["COMP9334", "System Capacity Planning"],
               ["COMP9415", "Computer Graphics"],
               ["COMP9447", "Security Engineering Workshop"],
               ["COMP4141", "Theory of Computation"],
               ["COMP4161", "Advanced Topics in Software Verification"],
               ["COMP6452", "Software Architecture for Blockchain Applications"],
               ["COMP6714", "Information Retrieval and Web Search"],
               ["COMP6721", "InFormal Methods: The Lost Art"],
               ["COMP6733", "Internet of Things Experimental Design Studio"],
               ["COMP6752", "Modelling Concurrent Systems"],
               ["COMP6771", "Advanced C++ Programming"],
               ["COMP6841", "Extended Security Engineering and Cyber Security"],
               ["COMP9102", "Programming Languages and Compilers"],
               ["COMP9151", "Foundations of Concurrency"],
               ["COMP9161", "Concepts of Programming Languages"],
               ["COMP9153", "Algorithmic Verification"],
               ["COMP9201", "Operating Systems"],
               ["COMP9283", "Extended Operating Systems"],
               ["COMP9211", "Computer Architecture"],
               ["COMP9313", "Big Data Management"],
               ["COMP9315", "Database Systems Implementation"],
               ["COMP9318", "Data Warehousing and Data Mining"],
               ["COMP9319", "Web Data Compression and Search"],
               ["COMP9332", "Network Routing and Switching"],
               ["COMP9333", "Advanced Computer Networks"],
               ["COMP9336", "Mobile Data Networking"],
               ["COMP9337", "Securing Wireless Networks"],
               ["COMP9417", "Machine Learning and Data Mining"],
               ["COMP9431", "Robotic Software Architecture"],
               ["COMP9444", "Neural Networks"],
               ["COMP9517", "Computer Vision"],
               ["COMP4121", "Advanced and Parallel Algorithms"],
               ["COMP6443", "Web Application Security Testing"],
               ["COMP6445", "Digital Forensics"],
               ["COMP6447", "System and Software Security Assessment"],
               ["COMP6448", "Security Engineering Masterclass"],
               ["COMP6741", "Parameterized and Exact Computation"],
               ["COMP6843", "Extended Web Application Security and Testing"],
               ["COMP6845", "Extended Digital Forensics and Incident Response"],
               ["COMP9242", "Advanced Operating Systems"],
               ["COMP9243", "Distributed Systems"],
               ["COMP9323", "Software as a Service Project"],
               ["COMP9418", "Advanced Topics in Statistical Machine Learning"],
               ["COMP9596", "Research Project"],
               ["COMP9900", "Information Technology Project"],
               ["COMP9945", "Research Project% "], ]
